package com.manuanand.stocksimulator;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/trade") // This means URL's start with /trade (after Application path)
public class TradeController {
	@Autowired // This means to get the bean called tradeRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private TradeRepository tradeRepository;

	@GetMapping(path="/")
	public @ResponseBody Iterable<Trade> getAllTrades() {
		
		// This returns a JSON or XML with the trades
		return tradeRepository.findAll();
	}

	@GetMapping(path="/{id}")
	public @ResponseBody Trade getSpecificTrade(@PathVariable String id) {
		
		Integer tradeId = null;
		try {
			tradeId = Integer.parseInt(id);
		} catch (NumberFormatException ex) {
			return null;
		}

		Optional<Trade> trade = tradeRepository.findById(tradeId);
		if (!trade.isEmpty()) {
			return trade.get();
		} 

		return null;
	}
}